// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddTask(arg1:string,arg2:string,arg3:string):Promise<models.Response>;

export function DeleteTask(arg1:number):Promise<models.Response>;

export function GetTasksCompleted():Promise<Array<models.Task>|models.Response>;

export function GetTasksNotCompleted():Promise<Array<models.Task>|models.Response>;

export function UpdateTask(arg1:number):Promise<models.Response>;
